theme: jekyll-theme-cayman


# Site Settings
locale                   : "en-US"
title                    : "Terraform"
#title_separator          : "-"
#name                     : &name "Your Name"
#description              : &description "personal description"
url                      : https://jhabboubi.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/terraform" # the subpath of your site, e.g. "/blog"
repository               : "jhabboubi/terraform"
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : true # true, false (default)
words_per_minute         : 160
# future                   : true
# read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
# talkmap_link             : false #change to true to add link to talkmap on talks page
# comments:
#   provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
#   disqus:
#     shortname            :
#   discourse:
#     server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
#   facebook:
#     appid                :
#     num_posts            : # 5 (default)
#     colorscheme          : # "light" (default), "dark"
# staticman:
#   allowedFields          : ['name', 'email', 'url', 'message']
#   branch                 : "gh-pages" # "master", "gh-pages"
#   commitMessage          : "New comment."
#   filename               : comment-{@timestamp}
#   format                 : "yml"
#   moderation             : true
#   path                   : "_data/comments/{options.slug}"
#   requiredFields         : ['name', 'email', 'message']
#   transforms:
#     email                : "md5"
#   generatedFields:
#     date:
#       type               : "date"
#       options:
#         format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
# atom_feed:
#   path                   : # blank (default) uses feed.xml
